In [3]:
DATA_DIR =  "../c3/namata-kdd11-data"
!ls $DATA_DIR

citeseer  cora	enron  FileFormat.txt  README

In [5]:
!ls $DATA_DIR/enron/enron-samples-lowunk/enron-sample-lowunk-1of6

sample-enron.DIRECTED.emailof.tab     sample-enron.NODE.person.tab
sample-enron.DIRECTED.sentto.tab      sample-enron.UNDIRECTED.coref.tab
sample-enron.GRAPH.communication.tab  sample-enron.UNDIRECTED.email-submgr.tab
sample-enron.NODE.email.tab	      sample-enron.UNDIRECTED.submgr.tab

In [50]:
import pandas as pd
import re

In [55]:
# used for extracting feature name

def get_feature(feature):
    feature_data = re.split(r"[:=]", feature)
    return feature_data

['emailaddress', 'bla...@gmail.com']

# Loading in the sparse, tab delimited node file

In [79]:
# initialize the pandas dataframe
node_data = pd.DataFrame()

with open('sample-enron.NODE.email.tab') as infile:
  i = 0
  for row in infile:
    if i == 0:
        # Skip non-useful first line
        print("Header: ", row)
    if i == 1:
        # Prepare dataframe column labels
        tokens = row.split()
        features = ["node"] + [get_feature(feature)[1] for feature in tokens]
        node_data = pd.DataFrame(columns=features)
    else:
        # Fill in rows
        tokens = row.split()
        node_data = pd.concat([node_data, pd.DataFrame({'node':[tokens[0]]}.update({}))], ignore_index=True)
        print('i is: ', i)
    i += 1

Header:  NODE	email

i is:  0
i is:  2
i is:  3
i is:  4
i is:  5
i is:  6
i is:  7
i is:  8
i is:  9
i is:  10
i is:  11
i is:  12
i is:  13
i is:  14
i is:  15
i is:  16
i is:  17
i is:  18
i is:  19
i is:  20
i is:  21
i is:  22
i is:  23
i is:  24
i is:  25
i is:  26
i is:  27
i is:  28
i is:  29
i is:  30
i is:  31
i is:  32
i is:  33
i is:  34
i is:  35
i is:  36
i is:  37
i is:  38
i is:  39
i is:  40
i is:  41
i is:  42
i is:  43
i is:  44
i is:  45
i is:  46
i is:  47
i is:  48
i is:  49
i is:  50
i is:  51
i is:  52
i is:  53
i is:  54
i is:  55
i is:  56
i is:  57
i is:  58
i is:  59
i is:  60
i is:  61
i is:  62
i is:  63
i is:  64
i is:  65
i is:  66
i is:  67
i is:  68
i is:  69
i is:  70
i is:  71
i is:  72
i is:  73
i is:  74
i is:  75
i is:  76
i is:  77
i is:  78
i is:  79
i is:  80
i is:  81
i is:  82
i is:  83
i is:  84
i is:  85
i is:  86
i is:  87
i is:  88
i is:  89
i is:  90
i is:  91
i is:  92
i is:  93
i is:  94
i is:  95
i is:  96
i is:  97
i is:  98
i is:  99
i is:  100
i is:  101
i is:  102
i is:  103
i is:  104
i is:  105
i is:  106
i is:  107
i is:  108
i is:  109
i is:  110
i is:  111
i is:  112
i is:  113
i is:  114
i is:  115
i is:  116
i is:  117
i is:  118
i is:  119
i is:  120
i is:  121
i is:  122
i is:  123
i is:  124
i is:  125
i is:  126
i is:  127
i is:  128
i is:  129
i is:  130
i is:  131
i is:  132
i is:  133
i is:  134
i is:  135
i is:  136
i is:  137
i is:  138
i is:  139
i is:  140
i is:  141
i is:  142
i is:  143
i is:  144
i is:  145
i is:  146
i is:  147
i is:  148
i is:  149
i is:  150
i is:  151
i is:  152
i is:  153
i is:  154
i is:  155
i is:  156
i is:  157
i is:  158
i is:  159
i is:  160
i is:  161
i is:  162
i is:  163
i is:  164
i is:  165
i is:  166
i is:  167
i is:  168
i is:  169
i is:  170
i is:  171
i is:  172
i is:  173
i is:  174
i is:  175
i is:  176
i is:  177
i is:  178
i is:  179
i is:  180
i is:  181
i is:  182
i is:  183
i is:  184
i is:  185
i is:  186
i is:  187
i is:  188
i is:  189
i is:  190
i is:  191
i is:  192
i is:  193
i is:  194
i is:  195
i is:  196
i is:  197
i is:  198
i is:  199
i is:  200
i is:  201
i is:  202
i is:  203
i is:  204
i is:  205
i is:  206
i is:  207
i is:  208
i is:  209
i is:  210
i is:  211
i is:  212

In [80]:
node_data

,node,emailaddress,numsent,numreceived,numexchanged,w-gerald,w-know,w-busi,w-mexicana,w-transact,...,w-bartlo,w-columbiagassubject,w-perron,w-coh,w-agl,w-kinney,w-veselack,w-mwhitt,w-jarnold,"other,manager,specialist,director,executive"
0,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
pd.DataFrame({'node':[69,420]})

   node
0    69
1   420